c.2,make,perl6,ocaml,objpascal: update to ubuntu:24.04
c.2:
    By updating to 24.04 we get around an error with declarations after
    labels which is allowed in more recent compiler versions.

make:
    With older make, the newer make code results in this error:
    ../make/readline.mk:13: *** unterminated call to function 'eval': missing ')'.  Stop.

    Newer versions of make work fine.

perl6:
    With older rakudo, this error occurs:
        user> (let* (DEBUG-EVAL false) (- 3 1))
        Cannot resolve caller Numeric(types::MalFalse: ); none of these signatures match:

ocaml:
    Fixes build error that happens with older versions of ocaml:
        ocamlopt -a types.ml reader.ml printer.ml env.ml core.ml -o mal_lib.cmxa
        File "env.ml", line 15, characters 8-21:
        Error: Unbound value Data.find_opt

objpascal:
    With older compiler, the following error occurs:
        user> (apply str (seq "this is a test"))
        *** Error in `../objpascal/stepA_mal': corrupted size vs. prev_size: 0x000000000246c360 ***